services:
  search-service:
    build:
      context: .
      dockerfile: core/search/Dockerfile
    container_name: search-service
    env_file:
      - ./core/search/.env
    volumes:
      - ./core/search:/app/search
    ports:
      - '8000:80'
    tty: true
    stdin_open: true
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 5s
      retries: 3
